<?php

namespace Database\Factories;

use App\Models\Org;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Org>
 */
class OrgFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Org::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $name = fake()->company();

        return [
            'name' => $name,
            'slug' => null, // Will be auto-generated by the model
            'country_code' => 'CI',
            'kyb_data' => null,
            'payout_channel' => null,
            'payout_identifier' => null,
            'verified' => false,
        ];
    }

    /**
     * Indicate that the organization is verified.
     */
    public function verified(): static
    {
        return $this->state(fn (array $attributes) => [
            'verified' => true,
        ]);
    }

    /**
     * Indicate that the organization has payout configured.
     */
    public function withPayout(string $channel = 'momo_mtn', ?string $identifier = null): static
    {
        return $this->state(fn (array $attributes) => [
            'payout_channel' => $channel,
            'payout_identifier' => $identifier ?? '+225' . fake()->numerify('##########'),
        ]);
    }

    /**
     * Indicate that the organization has KYB data.
     */
    public function withKyb(): static
    {
        return $this->state(fn (array $attributes) => [
            'kyb_data' => [
                'business_name' => $attributes['name'],
                'registration_number' => fake()->numerify('CI-###########'),
                'tax_id' => fake()->numerify('TIN-##########'),
                'address' => fake()->address(),
            ],
        ]);
    }
}
